#!/usr/bin/env bash
# demos/airgap.sh — the bundle air-gap round-trip, told out loud.
#
# Two agents that NEVER share a remote (or a network). One builds a ticked
# quilt and exports it to a single file; the original repo is then
# DESTROYED — the bundle is the only surviving copy (that's the air gap).
# On the far side the bundle is cloned and quilt-imported: hooks re-arm,
# and the journal (receipts + watch.log) regenerates from pure history,
# byte-identical to what the original actually observed. Then a fresh tick
# proves the far side is alive.
#
# Exits non-zero on the first failed assertion. Scratch under /tmp.

set -e

SRC="$(cd "$(dirname "$0")/.." && pwd)"
STAGE=$(mktemp -d /tmp/quilt-airgap-XXXXXX)

step()   { printf '\n=== %s\n' "$*"; }
assert() { # assert <description> <command...>
  local desc=$1; shift
  if "$@" >/dev/null 2>&1; then echo "  ok   $desc"
  else echo "  FAIL $desc"; echo "(scratch kept: $STAGE)"; exit 1; fi
}

gitq() { git -c commit.gpgsign=false \
              -c user.email=airgap@quilt.local \
              -c user.name=airgap-demo "$@"; }

# seed_cell <repo> <alias> — full dials + body, committed (already a tick)
seed_cell() {
  local repo=$1 alias=$2 i
  mkdir -p "$repo/cells/$alias/dials"
  echo "seed $alias" > "$repo/cells/$alias/body"
  for i in $(seq 0 15); do echo 0.0 > "$repo/cells/$alias/dials/$i"; done
  gitq -C "$repo" add cells
  gitq -C "$repo" commit -qm "cells: seed $alias"
}

step "1. build a ticked quilt at $STAGE/source"
SRC_REPO="$STAGE/source"
git init -q -b main "$SRC_REPO"
cp -R "$SRC/.quilt" "$SRC_REPO/.quilt"
gitq -C "$SRC_REPO" add -A
gitq -C "$SRC_REPO" commit -qm "skeleton: quilt runtime"
( cd "$SRC_REPO" && ./.quilt/bin/quilt-init ) >/dev/null

seed_cell "$SRC_REPO" auth
seed_cell "$SRC_REPO" billing
printf 'auth 0.5\n' > "$SRC_REPO/cells/billing/links"
gitq -C "$SRC_REPO" add cells/billing/links
gitq -C "$SRC_REPO" commit -qm "cells: billing links auth 0.5"

( cd "$SRC_REPO" && ./.quilt/bin/quilt-tick auth 1 0.9 )   # -> billing.dials/14 = 0.4500
( cd "$SRC_REPO" && ./.quilt/bin/quilt-tick billing 3 0.33 )

gitq -C "$SRC_REPO" add .quilt                            # fold the journal in
gitq -C "$SRC_REPO" commit -qm "journal: fold receipts + watch.log"
gitq -C "$SRC_REPO" update-ref refs/quilt/snap HEAD       # a quilt ref rides too

SNAP=$(gitq -C "$SRC_REPO" rev-parse refs/quilt/snap)
WATCH_LINES=$(wc -l < "$SRC_REPO/.quilt/watch.log" | tr -d '[:space:]')
echo "  history:"; gitq -C "$SRC_REPO" log --oneline | sed 's/^/    /'
echo "  watch.log ($WATCH_LINES ticks):"; sed 's/^/    /' "$SRC_REPO/.quilt/watch.log"

step "2. export the whole quilt to ONE file"
BUNDLE="$STAGE/quilt.bundle"
( cd "$SRC_REPO" && ./.quilt/bin/quilt-export "$BUNDLE" )
ls -lh "$BUNDLE" | awk '{print "  bundle:", $5, $9}'

step "3. AIR GAP — destroy the original repo"
rm -rf "$SRC_REPO"
assert "original repo is gone" test ! -d "$SRC_REPO"
echo "  the bundle file is now the only surviving copy of this quilt"

step "4. far side: clone the bundle, quilt-import it"
IMP="$STAGE/imported"
git clone -q "$BUNDLE" "$IMP"
( cd "$IMP" && ./.quilt/bin/quilt-import "$BUNDLE" )

step "5. assertions on the far side"
assert "hooks re-armed (core.hooksPath=.quilt/hooks)" \
  test "$(git -C "$IMP" config core.hooksPath)" = ".quilt/hooks"
assert "journal regenerated byte-identical to the carried one" \
  test -z "$(git -C "$IMP" status --porcelain -- .quilt/receipts .quilt/watch.log)"
assert "watch.log carries all $WATCH_LINES original ticks" \
  test "$(wc -l < "$IMP/.quilt/watch.log" | tr -d '[:space:]')" = "$WATCH_LINES"
assert "refs/quilt/snap survived the gap ($SNAP)" \
  test "$(git -C "$IMP" rev-parse refs/quilt/snap)" = "$SNAP"

( cd "$IMP" && ./.quilt/bin/quilt-tick auth 0 0.42 ) >/dev/null
IMP_SHORT=$(git -C "$IMP" rev-parse --short HEAD)
assert "fresh tick in the imported clone wrote a receipt" \
  test -f "$IMP/.quilt/receipts/$IMP_SHORT.json"
assert "watch.log grew by exactly one line" \
  test "$(wc -l < "$IMP/.quilt/watch.log" | tr -d '[:space:]')" = "$((WATCH_LINES + 1))"

step "6. state on the far side"
echo "  history:"; gitq -C "$IMP" log --oneline | head -4 | sed 's/^/    /'
echo "  watch.log tail:"; tail -2 "$IMP/.quilt/watch.log" | sed 's/^/    /'
echo "  receipts:"; ls "$IMP/.quilt/receipts" | tail -3 | sed 's/^/    /'

printf '\nairgap demo: PASS — synced two ticks and a journal across a dead remote\n'
rm -rf "$STAGE"
